version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: adminteste
      POSTGRES_PASSWORD: vS004Z
      POSTGRES_DB: orderdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Mapeia a porta 5432 do container para a porta 5433 local
    networks:
      - order-network

volumes:
  postgres_data:

networks:
  order-network:
    driver: bridge
